# Generated by Django 3.2.4 on 2021-06-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='data',
            new_name='date',
        ),
    ]
