# Generated by Django 3.2.4 on 2021-06-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.blog'),
        ),
    ]
